/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CartItem { 'productId' : ProductId, 'quantity' : bigint }
export interface CartSummary {
  'itemCount' : bigint,
  'items' : Array<CartItem>,
  'subtotal' : bigint,
}
export type Category = { 'watches' : null } |
  { 'bags' : null } |
  { 'clothes' : null } |
  { 'shoes' : null } |
  { 'computers' : null } |
  { 'electronics' : null };
export interface Order {
  'id' : OrderId,
  'status' : OrderStatus,
  'total' : bigint,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'updatedAt' : Timestamp,
  'shippingAddress' : ShippingAddress,
  'items' : Array<OrderItem>,
  'stripeSessionId' : string,
}
export type OrderId = bigint;
export interface OrderInput {
  'shippingAddress' : ShippingAddress,
  'items' : Array<OrderItem>,
  'stripeSessionId' : string,
}
export interface OrderItem {
  'productId' : ProductId,
  'productName' : string,
  'quantity' : bigint,
  'priceAtPurchase' : bigint,
}
export type OrderStatus = { 'shipped' : null } |
  { 'cancelled' : null } |
  { 'pending' : null } |
  { 'delivered' : null };
export interface Product {
  'id' : ProductId,
  'name' : string,
  'createdAt' : Timestamp,
  'description' : string,
  'stock' : bigint,
  'category' : Category,
  'price' : bigint,
  'images' : Array<ProductImage>,
}
export type ProductId = bigint;
export type ProductImage = Uint8Array;
export interface ProductInput {
  'name' : string,
  'description' : string,
  'stock' : bigint,
  'category' : Category,
  'price' : bigint,
  'images' : Array<ProductImage>,
}
export interface ShippingAddress {
  'country' : string,
  'city' : string,
  'postalCode' : string,
  'fullName' : string,
  'state' : string,
  'addressLine1' : string,
  'addressLine2' : string,
  'phone' : string,
}
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export type SortOption = { 'newest' : null } |
  { 'priceDesc' : null } |
  { 'priceAsc' : null };
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export type Timestamp = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export type UserId = Principal;
export interface UserProfile { 'name' : string, 'email' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'addProduct' : ActorMethod<[ProductInput], Product>,
  'addToCart' : ActorMethod<[ProductId, bigint], CartSummary>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'clearCart' : ActorMethod<[], undefined>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'deleteProduct' : ActorMethod<[ProductId], boolean>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCart' : ActorMethod<[], CartSummary>,
  'getOrder' : ActorMethod<[OrderId], [] | [Order]>,
  'getProduct' : ActorMethod<[ProductId], [] | [Product]>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getUserProfile' : ActorMethod<[UserId], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'listAllOrders' : ActorMethod<[], Array<Order>>,
  'listMyOrders' : ActorMethod<[], Array<Order>>,
  'listProducts' : ActorMethod<
    [[] | [Category], [] | [string], [] | [SortOption]],
    Array<Product>
  >,
  'placeOrder' : ActorMethod<[OrderInput], Order>,
  'removeFromCart' : ActorMethod<[ProductId], CartSummary>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateCartItemQuantity' : ActorMethod<[ProductId, bigint], CartSummary>,
  'updateOrderStatus' : ActorMethod<[OrderId, OrderStatus], [] | [Order]>,
  'updateProduct' : ActorMethod<[ProductId, ProductInput], [] | [Product]>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];